### ISSUE TITLE
ThemeManager running before widgets are created

### ISSUE THREAD

**Issue by Bromson3105** [Thisal-D/ctkchart#15]
I tried adding the example presented in [Simple Guide](https://github.com/Thisal-D/ctkchart#simple-guide). I got only to the part where the plot is created (before adding the line), and if I run that I get the exception "Line Chart theme configure failed : 'CTkLineChart' object has no attribute '_CTkLineChart__y_axis_frame'".

Going through the code, I see that the ThemeManager is [being called to run](https://github.com/Thisal-D/ctkchart/blob/731c78b00a97f8939fae0cfcc007d20cd5a37ebf/src/ctkchart/CTkLineChart.py#L65) before [the widgets are created](https://github.com/Thisal-D/ctkchart/blob/731c78b00a97f8939fae0cfcc007d20cd5a37ebf/src/ctkchart/CTkLineChart.py#L253).

If I simply move the block
```
"""
Initialize Theme manager
"""
ThemeManager.bind_widget(self)
if ThemeManager.running_state is not True:
    ThemeManager.run()
```
to after `self.__create_widgets()` I don't get the exception anymore.

I haven't dug deep enough to see if this has any other undesired effects.

**To Reproduce**
1. Import ctkchart
2. Execute:
```
chart = ctkchart.CTkLineChart(
    master=self.chart_frame,
    x_axis_values=("a", "b", "c", "d", "e", "f"),
    y_axis_values=(100, 900),
)
```

**Additional context**
I am not running this at the moment my app starts, this is trigger after I go through a few screens and open a TopLevel. I mention this in case the fact that the app is running for a bit (a couple of seconds) before I call `CTkLineChart` is meaningful in any way.

**Note**
The exception doesn't occur when I launch the app, it happens once it passes by the code block I showed in the "To Reproduce" section

**Comment by Thisal-D** [comment]
Thank you for taking the time to report this issue and for providing detailed feedback. I appreciate your effort in investigating the code and suggesting a potential fix. Feedback like yours helps improve the project significantly.

I fixed the issue using your ideas (calling the theme manager after creating the chart object). The updated version is now available; please update to the latest release and let me know if you encounter any further issues.

**Thank you once again for contributing to the project and helping make it better**

**Comment by Bromson3105** [comment]
Just here to confirmed that the update fixed it for me as well. Thank you for the prompt fix!
