### ISSUE TITLE
Easing

### ISSUE THREAD

**Issue by byte127x** [Thisal-D/ctkchart#8]
can you add easing to the animated graphs?
like when the graph is being drawn instead of one line at a time, it can draw slow then fast then slow for each line or the whole thing
just something that would be cool

**Comment by Thisal-D** [comment]
> can you add easing to the animated graphs? like when the graph is being drawn instead of one line at a time, it can draw slow then fast then slow for each line or the whole thing just something that would be cool

Can you explain this more clearly? I didn't understand exactly what you are trying to say.
